export const ingredients = {
"Alit_Hide": ["Drain Intelligence", "Resist Poison", "Telekinesis", "Detect Animal"],
"Ampoule_Pod": ["Water Walking", "Paralyze", "Detect Animal", "Drain Willpower"],
"Ash_Salts": ["Drain Agility", "Resist Magicka", "Cure Blight Disease", "Resist Magicka"],
"Ash_Yam": ["Fortify Intelligence", "Fortify Strength", "Resist Common Disease", "Detect Key"],
"Bittergreen_Petals": ["Restore Intelligence", "Invisibility", "Drain Endurance", "Drain Magicka"],
"Black_Anther": ["Drain Agility", "Resist Fire", "Drain Endurance", "Light"],
"Black_Lichen": ["Drain Strength", "Resist Frost", "Drain Speed", "Cure Poison"],
"Bloat": ["Drain Magicka", "Fortify Intelligence", "Fortify Willpower", "Detect Animal"],
"Bonemeal": ["Restore Agility", "Telekinesis", "Drain Fatigue", "Drain Personality"],
"Bread": ["Restore Fatigue", "-", "-", "-"],
"Bungler's_Bane": ["Drain Speed", "Drain Endurance", "Dispel", "Drain Strength"],
"Chokeweed": ["Drain Luck", "Restore Fatigue", "Cure Common Disease", "Drain Willpower"],
"Coda_Flower": ["Drain Personality", "Levitate", "Drain Intelligence", "Drain Health"],
"Comberry": ["Drain Fatigue", "Restore Magicka", "Fire Shield", "Reflect"],
"Corkbulb_Root": ["Cure Paralyzation", "Restore Health", "Lightning Shield", "Fortify Luck"],
"Corprus_Weepings": ["Drain Fatigue", "Fortify Luck", "Drain Willpower", "Restore Health"],
"Crab_Meat": ["Restore Fatigue", "Resist Shock", "Lightning Shield", "Restore Luck"],
"Daedra_Skin": ["Fortify Strength", "Cure Common Disease", "Paralyze", "Swift Swim"],
"Daedra's_Heart": ["Restore Magicka", "Fortify Endurance", "Drain Agility", "Night-Eye"],
"Diamond": ["Drain Agility", "Invisibility", "Reflect", "Detect Key"],
"Dreugh_Wax": ["Fortify Strength", "Restore Strength", "Drain Luck", "Drain Willpower"],
"Ectoplasm": ["Fortify Agility", "Detect Animal", "Drain Strength", "Drain Health"],
"Emerald": ["Fortify Magicka", "Restore Health", "Drain Agility", "Drain Endurance"],
"Fire_Petal": ["Resist Fire", "Drain Health", "Spell Absorption", "Paralyze"],
"Fire_Salts": ["Drain Health", "Fortify Agility", "Resist Frost", "Fire Shield"],
"Frost_Salts": ["Drain Speed", "Restore Magicka", "Frost Shield", "Resist Fire"],
"Ghoul_Heart": ["Paralyze", "Cure Poison", "Fortify Attack", "-"],
"Girith's_Guar_Hide": ["Drain Fatigue", "Fortify Endurance", "Restore Personality", "Fortify Luck"],
"Gold_Kanet": ["Drain Health", "Burden", "Drain Luck", "Restore Strength"],
"Gravedust": ["Drain Intelligence", "Cure Common Disease", "Drain Magicka", "Restore Endurance"],
"Green_Lichen": ["Fortify Personality", "Cure Common Disease", "Drain Strength", "Drain Health"],
"Guar_Hide": ["Drain Fatigue", "Fortify Endurance", "Restore Personality", "Fortify Luck"],
"Hackle-Lo_Leaf": ["Restore Fatigue", "Paralyze", "Water Breathing", "Restore Luck"],
"Heather": ["Restore Personality", "Feather", "Drain Speed", "Drain Personality"],
"Hound_Meat": ["Restore Fatigue", "Fortify Fatigue", "Reflect", "Detect Enchantment"],
"Human_Flesh": ["Fortify Health", "Drain Intelligence", "Drain Personality", "-"],
"Hypha_Facia": ["Drain Luck", "Drain Agility", "Drain Fatigue", "Detect Enchantment"],
"Kagouti_Hide": ["Drain Fatigue", "Fortify Speed", "Resist Common Disease", "Night-Eye"],
"Kresh_Fiber": ["Restore Luck", "Fortify Personality", "Drain Magicka", "Drain Speed"],
"Kwama_Cuttle": ["Resist Poison", "Drain Fatigue", "Water Walking", "Water Breathing"],
"Large_Corprusmeat_Hunk": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Large_Kwama_Egg": ["Restore Fatigue", "Paralyze", "Frost Shield", "Fortify Health"],
"Large_Wrapped_Corprusmeat": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Luminous_Russula": ["Water Breathing", "Drain Fatigue", "Poison", "-"],
"Marshmerrow": ["Restore Health", "Detect Enchantment", "Drain Willpower", "Drain Fatigue"],
"Marsus'_Guar_Hide": ["Drain Fatigue", "Fortify Endurance", "Restore Personality", "Fortify Luck"],
"Medium_Corprusmeat_Hunk": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Medium_Wrapped_Corprusmeat": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Meteor_Slime": ["Fortify Willpower", "Cure Poison", "Cure Blight Disease", "Restore Willpower"],
"Moon_Sugar": ["Fortify Speed", "Dispel", "Drain Endurance", "Drain Luck"],
"Muck": ["Drain Intelligence", "Detect Key", "Drain Personality", "Cure Common Disease"],
"Muffin_(Morrowind)": ["Restore Fatigue", "-", "-", "-"],
"Netch_Leather": ["Fortify Endurance", "Fortify Intelligence", "Drain Personality", "Cure Paralyzation"],
"Pearl": ["Drain Agility", "Dispel", "Water Breathing", "Resist Common Disease"],
"Poison": ["Weakness to Poison", "Damage Health", "Damage Fatigue", "Poison"],
"Racer_Plumes": ["Drain Willpower", "Levitate", "-", "-"],
"Rat_Meat": ["Drain Magicka", "Paralyze", "Cure Poison", "Resist Poison"],
"Raw_Ebony": ["Drain Agility", "Cure Poison", "Frost Shield", "Restore Speed"],
"Raw_Glass": ["Drain Intelligence", "Drain Strength", "Drain Speed", "Fire Shield"],
"Red_Lichen": ["Drain Speed", "Light", "Cure Common Disease", "Drain Magicka"],
"Resin": ["Restore Health", "Restore Speed", "Burden", "Resist Common Disease"],
"Roland's_Tears": ["Drain Health", "Burden", "Drain Luck", "Restore Strength"],
"Roobrush": ["Drain Willpower", "Fortify Agility", "Drain Health", "Cure Poison"],
"Ruby": ["Drain Health", "Feather", "Restore Intelligence", "Drain Agility"],
"Saltrice": ["Restore Fatigue", "Fortify Magicka", "Drain Strength", "Restore Health"],
"Scales": ["Drain Personality", "Water Walking", "Restore Endurance", "Swift Swim"],
"Scamp_Skin": ["Drain Magicka", "Cure Paralyzation", "Restore Personality", "Restore Strength"],
"Scathecraw": ["Drain Strength", "Cure Poison", "Drain Health", "Restore Willpower"],
"Scrap_Metal": ["Drain Health", "Lightning Shield", "Resist Shock", "Restore Intelligence"],
"Scrib_Jelly": ["Fortify Willpower", "Cure Poison", "Cure Blight Disease", "Restore Willpower"],
"Scrib_Jerky": ["Restore Fatigue", "Fortify Fatigue", "Burden", "Swift Swim"],
"Scuttle": ["Restore Fatigue", "Fortify Fatigue", "Feather", "Telekinesis"],
"Shalk_Resin": ["Drain Fatigue", "Fortify Health", "Drain Personality", "Fortify Speed"],
"Sload_Soap": ["Drain Personality", "Fortify Agility", "Fire Shield", "Restore Agility"],
"Small_Corprusmeat_Hunk": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Small_Kwama_Egg": ["Restore Fatigue", "-", "-", "-"],
"Small_Wrapped_Corprusmeat": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"],
"Spore_Pod": ["Drain Strength", "Drain Fatigue", "Detect Key", "Paralyze"],
"Stoneflower_Petals": ["Restore Strength", "Fortify Magicka", "Drain Luck", "Fortify Personality"],
"Trama_Root": ["Restore Willpower", "Levitate", "Drain Magicka", "Drain Speed"],
"Treated_Bittergreen_Petals": ["Restore Intelligence", "Drain Magicka", "Drain Endurance", "Invisibility"],
"Vampire_Dust": ["Fortify Health", "Fortify Strength", "Spell Absorption", "Vampirism"],
"Violet_Coprinus": ["Water Walking", "Drain Fatigue", "Poison", "-"],
"Void_Salts": ["Restore Magicka", "Spell Absorption", "Paralyze", "Drain Endurance"],
"Wickwheat": ["Restore Health", "Fortify Willpower", "Paralyze", "Damage Intelligence"],
"Willow_Anther": ["Drain Personality", "Frost Shield", "Cure Common Disease", "Cure Paralyzation"],
"Wrapped_Corprusmeat_Hunk": ["Drain Fatigue", "Drain Health", "Drain Magicka", "-"]
}
